### PR TITLE
add OEM and shared modes

### PR DESCRIPTION
**Pull request by danielnachun**
Here is my very rough first pass at implementing most of the changes we've been discussing.  A few key things for discussion:

- For `mm_jobman.sh`, the changes are actually minimal - we just have to update the generated job script a bit so that instead of using an entrypoint, it just symlinks the necessary folders from `/mnt/efs/oem` to `${HOME}`.  I did not anything sophisticated to make the links read-only - I just used `chmod -w`.  I think for now we can assume our users are not malicious and will not deliberately try to re-enable write permission to break or compromise our software, but may be we can find a more robust way to do this later.
- For `mm_interactive.sh`, right now I'm opting for the simpler "3 mode solution" where we don't try to let the user specify different linking paths themselves.  This is because we are running `bind_mount.sh` as the job script and it's not clear to me if it can take command line arguments.  However we can pass it an environment variable `MODE` that we can then parse in `bind_mount.sh`.  I added a bit of logic to make sure the user doesn't try to enable both `--oem-admin` and `--shared-admin` at the same time as this would make no sense, and also to make sure that `--mount-packages` is specified alongside those options, as `bind_mount.sh` needs to be run for those new options to have any effect
- For `bind_mount.sh`, I had to make the most complex changes to account for the different modes.  We always want to link `.pixi` and `micromamba` between the EFS mount and our local folders, but the destination of those links will depend a bit on the mode we are in.  And we only want to link all the config files if we are linking from the user's personal folder on the EFS mount.  I think we may need a couple of the config files for `pixi` and `micromamba` installation stuff to work correctly in the admin modes, so we may have link those.  But for now are not supporting any of Jupyter, VSCode or RStudio in the admin modes, so we don't need to link any config files needed for those.

One key thing I haven't touched is `host_init.sh`. It's not clear to me if we can pass environment variables or command line arguments to that script, so I'm wondering if we'll just need two different scripts for mounting our regular volume and our "OEM' volume, as we'll never need to mount both in the same job.  I also don't have the IP address for the OEM EFS volume (I'm assuming this has to be created first?) so I haven't tried to write anything for this yet.

Please let me know what you think so far.  Once we have these changes to start with, it should be easier to iterate on this until we have something works.

### CODE REVIEW

**Comment by Ashley-Tung** [comment]
Overall, I think this looks good! In regards to `host_init.sh`, that wil require some changes, but for what I am envisioning we would just need to:
* depending on if running batch or interactive jobs, we would specify the corresponding EFS to mount
* create the directories in the EFS if they do not exist already
    * In batch mode, user do not have to do this explicitly, since packages should be preinstalled for first-time users anyway
    * In interactive mode, they would basically only have empty folders for their installations when setting up for the first time, same thing as the interactive solution now

In regards to `bind_mount.sh`, I believe it looks good for the interactive jobs, but for batch jobs, users would also be submitting their own job script. Since MMC cannot take more than one job script AND `--containerInit` unfortunately does not run at the beginnning of container initialization (i double-checked with Engineering on this), we would have to basically combine `bind_mount.sh` with the generated script.

You can see in lines https://github.com/Ashley-Tung/mmcloud_columbia/pull/1/files#diff-ba5bb77f1105c134531fd5e9bdcb8f9da221dd56f5392b8bf74136b4cc1b8cd5R516-R570 we generate the pipeline job script. We would need to get the contents of `bind_mount.sh` into here as well so that the `bind_mount` portion runs before the pipeline portion in the job

Let me know if this makes sense. Thank you again for submitting the PR!

**Comment by danielnachun** [comment]
> Overall, I think this looks good! In regards to `host_init.sh`, that wil require some changes, but for what I am envisioning we would just need to:
> 
> * depending on if running batch or interactive jobs, we would specify the corresponding EFS to mount
> * create the directories in the EFS if they do not exist already
>   
>   * In batch mode, user do not have to do this explicitly, since packages should be preinstalled for first-time users anyway
>   * In interactive mode, they would basically only have empty folders for their installations when setting up for the first time, same thing as the interactive solution now

Would it make sense to have a different `host_init.sh` script for batch jobs?  Or can we pass environment variables to this script so that we can have an if statement to change the EFS volume IP?  We would also skip the directory creation in batch mode.

> In regards to `bind_mount.sh`, I believe it looks good for the interactive jobs, but for batch jobs, users would also be submitting their own job script. Since MMC cannot take more than one job script AND `--containerInit` unfortunately does not run at the beginnning of container initialization (i double-checked with Engineering on this), we would have to basically combine `bind_mount.sh` with the generated script.
> 
> You can see in lines https://github.com/Ashley-Tung/mmcloud_columbia/pull/1/files#diff-ba5bb77f1105c134531fd5e9bdcb8f9da221dd56f5392b8bf74136b4cc1b8cd5R516-R570 we generate the pipeline job script. We would need to get the contents of `bind_mount.sh` into here as well so that the `bind_mount` portion runs before the pipeline portion in the job

I already added these lines in this PR in place of `${entrypoint}` in the job script generation in `mm_jobman.sh`:
```
# Symlink /mnt/efs/oem folders to \${HOME} to make software available
username=\$(whoami)
chmod -w /mnt/efs/oem
ln -sf /mnt/efs/oem/.pixi /home/\${username}/.pixi
ln -sf /mnt/efs/oem/micromamba /home/\${username}/micromamba
export PATH="\${HOME}/.pixi/bin:\${PATH}"
```
I don't think we need anything else from `bind_mount.sh` because the other code in there is just for:
- linking more directories we probably don't need for batch jobs (we could any others that do end up being needed)
- creating `.bashrc` and `.profile` which probably aren't needed for batch jobs
- the entrypoint for launching interactive environments, which we also don't need for batch jobs

If it turns out we do need more parts of `bind_mount.sh` in the job script generation, these can of course be added as needed later.

**Comment by Ashley-Tung** [comment]
> Would it make sense to have a different host_init.sh script for batch jobs? Or can we pass environment variables to this script so that we can have an if statement to change the EFS volume IP? We would also skip the directory creation in batch mode.

Yes, good point on making a separate `host_init.sh` script! It would make things neater for interactive and batch jobs. Would you be free to work on that? I am unfortunately still out at a workshop. I can make an extra EFS and share the IP here.

> I already added these lines in this PR in place of ${entrypoint} in the job script generation in mm_jobman.sh

Thanks for that, I didn't notice that! Then, I think we are good to go after making that new `host_init.sh`!

**Comment by Ashley-Tung** [comment]
With a new EFS for batch jobs, we can replace [the original EFS line](https://github.com/Ashley-Tung/mmcloud_columbia/blob/main/src/host_init.sh#L13) with
```
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 10.1.10.231:/ /mnt/efs
```
for the `host_init.sh` for batch jobs

**Comment by danielnachun** [comment]
Thanks, the IP is the main thing I needed.  I'll for now rename the original `host_init.sh` to `host_init_interactive.sh`, and create a new `host_init_batch.sh` with the different IP address you shared.  I'll also update script names in `mm_jobman.sh` and `mm_interactive.sh` to match those new names.

**Comment by Ashley-Tung** [comment]
Sounds good, thank you Daniel! Let me know when it is done

**Comment by danielnachun** [comment]
I think i got everything updated for `host_init` now.  One minor detail I'm still not sure about is that for `--shared-admin` mode, we don't want to create directories in `/mnt/efs/$FLOAT_USER` but instead in `/mnt/efs/shared`.  Maybe we actually need 3 host init scripts for now?  `host_init_user`, `host_init_oem_admin` and `host_init_shared_admin`?  Let me know what you think.

**Comment by Ashley-Tung** [comment]
Thanks @danielnachun , i think it looks good! I am going to merge the PR with this repo so I can do some tests. 

The testing will mainly be on the float CLI side, as I do not have a list of the packages to install for batch and interactive.

**Comment by danielnachun** [comment]
For now let's just test something simple like `pixi global install hello` and make sure it's actually accessible from a batch job after installing it in `oem-admin` mode, and that it's seen in the sym-linked `/opt/.pixi/bin` folder in a regular interactive mode.

**Comment by Ashley-Tung** [comment]
Great, i can try that for a batch job. However, for batch jobs, there is no `oem-admin` mode. That mode only exists in interactive. Check the unresolved comment above

**Comment by danielnachun** [comment]
The idea is to install the package in an **interactive** job with `--oem-admin` mode, and then run a **batch** job that tries to use that package, and this batch job is just run "normally" (with our new `host_init_batch.sh` and the updated job script generation).  No need for a `--oem-admin` mode for the batch job.

**Comment by Ashley-Tung** [comment]
Understood, i think that was the one piece of information i was missing. I can test with the small `pixi global install hello` tomorrow. Thank you!

**Comment by Ashley-Tung** [comment]
I just realized something then. If i as an admin want to install packages for batch jobs, I would have to go through `mm_interactive` to install it. However, the `host_init_interactive.sh` uses the interactive EFS `10.1.10.236`. 

This means packages meant for batch jobs in `oem_admin` mode will end up being in the interactive job EFS, and we do not want there to be individual `$FLOAT_USER` folders in the batch EFS. 

I think it might be best if we use  `host_init_batch` when setting up `oem-admin`. What do you think?

**Pull request merged**
